TrainerNames:
	db "YOUNGSTER@"
	db "BUG CATCHER@"
	db "LASS@"
	db "SAILOR@"
	db "JR.TRAINER♂@"
	db "JR.TRAINER♀@"
	db "POKéMANIAC@"
	db "SUPER NERD@"
	db "HIKER@"
	db "BIKER@"
	db "BURGLAR@"
	db "ENGINEER@"
	db "SWIMMER♀@"
	db "FISHERMAN@"
	db "SWIMMER♂@"
	db "CUE BALL@"
	db "GAMBLER@"
	db "BEAUTY@"
	db "PSYCHIC@"
	db "ROCKER@"
	db "JUGGLER@"
	db "TAMER@"
	db "BIRD KEEPER@"
	db "BLACKBELT@"
	db "RIVAL@"
	db "PROF.OAK@"
	db "LEADER@"
	db "SCIENTIST@"
	db "BOSS@"
	db "ROCKET@"
	db "COOLTRAINER♂@"
	db "COOLTRAINER♀@"
	db "ELITE FOUR@"
	db "LEADER@"
	db "LEADER@"
	db "LEADER@"
	db "LEADER@"
	db "LEADER@"
	db "LEADER@"
	db "LEADER@"
	db "GENTLEMAN@"
	db "RIVAL@"
	db "CHAMPION@"
	db "ELITE FOUR@"
	db "CHANNELER@"
	db "ELITE FOUR@"
	db "ELITE FOUR@"
